# --- Standard Library and Third-Party Imports ---
import random
import sys
import os
import argparse
import logging
import numpy as np
import tqdm
import cv2

# --- PyTorch Core and Distributed Training Imports ---
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torch.distributed as dist
from torch.utils.data import DataLoader
from torch.utils.data.distributed import DistributedSampler

# --- Add Parent Directory to Path to load custom modules ---
parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(parent_dir)

# --- Custom Module Imports ---
from dataloader import Multi_GoPro_Loader, RealBlur_Loader
from MIMO_UNet.models.LatentEncoder import LE_arch
from MIMO_UNet.models.LatentBlurDM import LatentExposureDiffusion # Diffusion Model/Latent Predictor
from MIMO_UNet.models.losses import CharbonnierLoss, VGGPerceptualLoss, L1andPerceptualLoss
from utils.utils import calc_psnr, same_seed, count_parameters, tensor2cv, AverageMeter, judge_and_remove_module_dict

# --- Image Quality Assessment and Logging ---
import pyiqa
from tensorboardX import SummaryWriter

# --- Environment and CUDNN Configuration ---
# Prevent OpenCV from utilizing multiple threads, which can cause deadlocks in PyTorch DataLoaders
cv2.setNumThreads(0)
# Enable cuDNN optimizations for faster training on GPUs
torch.backends.cudnn.enabled = True
torch.backends.cudnn.benchmark = True
# Ensure reproducible results by forcing deterministic algorithms
torch.backends.cudnn.deterministic = True

# --- FFT Compatibility Polyfill ---
# Retained for compatibility, though seemingly unused in this specific stage's loss function
try:
    from torch import rfft
except ImportError:
    def rfft(x, d):
        t = torch.fft.fft(x, dim=(-d))
        r = torch.stack((t.real, t.imag), -1)
        return r

class Trainer():
    """
    Main Trainer class handling the training loop, validation loop, model saving, and logging.
    This stage focuses on training a Latent Diffusion Model (model_dm) to predict the 
    latent representation generated by a frozen Latent Encoder (model_le).
    """
    def __init__(self, dataloader_train, dataloader_val, model_le, model_dm, optimizer, scheduler, args, writer) -> None:
        self.dataloader_train = dataloader_train
        self.dataloader_val = dataloader_val
        self.model_le = model_le   # Pre-trained, frozen Latent Encoder (Teacher)
        self.model_dm = model_dm   # Latent Diffusion Model being trained (Student/Predictor)
        self.optimizer = optimizer
        self.scheduler = scheduler
        self.args = args
        self.writer = writer
        self.epoch = 0
        self.device = self.args.device
        self.grad_clip = 1

        # Setup learning rate scheduler bounds
        self.scheduler.T_max = self.args.end_epoch
        
        # Select the criterion (loss function) for matching latent representations
        if args.criterion == "l1":
            self.criterion = CharbonnierLoss()
        elif args.criterion == "perceptual":
            self.criterion = VGGPerceptualLoss().to(device)
        elif args.criterion == "l1perceptual":
             self.criterion = L1andPerceptualLoss(gamma=args.gamma).to(device)
        else:
            raise ValueError(f"criterion not supported {args.criterion}")
        
    def train(self):
        """Main training loop iterating over epochs."""
        # Only print global training info on the master process (Rank 0)
        if dist.get_rank() == 0:
            print('###########################################')
            print('Start_Epoch:', self.args.start_epoch)
            print('End_Epoch:', self.args.end_epoch)
            print('Model:', self.args.model_name)
            print(f"Optimizer:{self.optimizer.__class__.__name__}")
            print(f"Scheduler:{self.scheduler.__class__.__name__ if self.scheduler else None}")
            print(f"Train Data length:{len(dataloader_train.dataset)}")
            print("start train !!")
            print('###########################################')

        # Iterate from the starting epoch to the end epoch
        for epoch in range(args.start_epoch, args.end_epoch + 1):
            self.epoch = epoch
            self._train_epoch()

            # Rank 0 handles validation, image saving, and checkpoint saving
            if dist.get_rank() == 0:
                if (epoch % self.args.validation_epoch) == 0 or epoch == self.args.end_epoch:
                    self.valid()

                if(self.args.val_save_epochs > 0 and epoch % self.args.val_save_epochs == 0 or epoch == self.args.end_epoch):
                    self.val_save_image(dir_path=self.args.dir_path, dataset=self.dataloader_val.dataset)

                self.save_model()
    
    def _train_epoch(self):
        """Handles a single epoch of training."""
        # Ensure the distributed sampler shuffles data differently each epoch
        train_sampler.set_epoch(self.epoch)
        tq = tqdm.tqdm(self.dataloader_train, total=len(self.dataloader_train))
        tq.set_description(f'Epoch [{self.epoch}/{self.args.end_epoch}] training')
        
        total_train_loss = AverageMeter()
        total_train_psnr = AverageMeter()   # Unused in this stage but kept for meter structure
        total_train_lpips = AverageMeter()  # Unused in this stage but kept for meter structure
        
        for idx, sample in enumerate(tq):
            # VERY IMPORTANT: Latent Encoder is frozen (eval mode), Diffusion Model is training
            self.model_le.eval()
            self.model_dm.train()
            self.optimizer.zero_grad()
            
            # Fetch blurred and sharp (ground truth) images
            blur, sharp = sample['blur'].to(device), sample['sharp'].to(device)
            
            # Forward pass: Generate Ground Truth latent representation from frozen model_le
            # model_le has seen both blur and sharp in Stage 1 to learn a good representation
            z_gt = self.model_le(blur, sharp)
            
            # Forward pass: model_dm tries to predict that latent representation using ONLY the blurred image
            z_pred = self.model_dm(blur)

            # Loss calculation: How close is the predicted latent to the "true" latent?
            loss_prior = self.criterion(z_pred, z_gt)

            loss = loss_prior
            loss.backward()

            # Optional: Gradient clipping
            #torch.nn.utils.clip_grad_norm_(self.model.parameters(), self.grad_clip)

            self.optimizer.step()

            # Update metrics
            total_train_loss.update(loss.detach().item())
            
            # Image PSNR/LPIPS are commented out because we are comparing latents, not pixels here
            # psnr = calc_psnr(outputs[2].detach(), sharp.detach())
            # total_train_psnr.update(psnr)

            tq.set_postfix({'loss': total_train_loss.avg,'lr': optimizer.param_groups[0]['lr']})

        # Update learning rate schedule
        if self.scheduler:
            self.scheduler.step()
            
        # Log to Tensorboard and text log on Master process
        if self.writer and dist.get_rank() == 0:
            self.writer.add_scalar('Loss/Train_loss', total_train_loss.avg, self.epoch)
            logging.info(
                f'Epoch [{self.epoch}/{args.end_epoch}]: Train_loss: {total_train_loss.avg:.4f}')
    
    @torch.no_grad()
    def _valid(self, blur, sharp):
        """Processes a single validation batch."""
        self.model_le.eval()
        self.model_dm.eval()
        
        # Generate target latent and predicted latent
        z_gt = self.model_le(blur, sharp)
        z_pred = self.model_dm(blur)

        # Calculate latent matching loss
        loss_prior = self.criterion(z_pred, z_gt)

        loss = loss_prior
        # Return dummy values (0) for PSNR and LPIPS as they aren't calculated in this latent space
        return 0, 0, loss.item()
    
    @torch.no_grad()
    def valid(self):
        """Loops through the validation dataset and logs performance."""
        self.model_le.eval()
        self.model_dm.eval()
      
        total_val_loss = AverageMeter()
        tq = tqdm.tqdm(self.dataloader_val, total=len(self.dataloader_val))
        tq.set_description(f'Epoch [{self.epoch}/{self.args.end_epoch}] Validation')
        
        for idx, sample in enumerate(tq):
            blur, sharp = sample['blur'].to(device), sample['sharp'].to(device)
            psnr, lpips, loss = self._valid(blur, sharp)
            total_val_loss.update(loss)
            tq.set_postfix(Loss=total_val_loss.avg)

        self.writer.add_scalar('Val/Test_loss', total_val_loss.avg, self.epoch)
        logging.info(
            f'Crop Validation Epoch [{self.epoch}/{args.end_epoch}]: Test Loss: {total_val_loss.avg:.4f} ')

        # Always save the latest Diffusion Model state during validation
        best_state = {'model_dm_state': self.model_dm.module.state_dict(), 'args': args}
        torch.save(best_state, os.path.join(args.dir_path, 'last_dm_{}.pth'.format(args.model_name)))
            
    def save_model(self):
        """Saves current state of the diffusion model, optimizer, and scheduler."""
        training_state = {'epoch': self.epoch, 
                          'model_dm_state': self.model_dm.module.state_dict(),
                          'optimizer_state': self.optimizer.state_dict(),
                          'scheduler_state': self.scheduler.state_dict() if self.scheduler else None,
                          'args': args}
        
        # Overwrite the latest checkpoint
        torch.save(training_state, os.path.join(self.args.dir_path, 'last_{}.pth'.format(self.args.model_name)))

        # Save milestone checkpoints periodically
        if (self.epoch % self.args.check_point_epoch) == 0:
            torch.save(training_state, os.path.join(self.args.dir_path, 'epoch_{}_{}.pth'.format(self.epoch, self.args.model_name)))

        # Save the final model cleanly at the end of training
        if self.epoch == self.args.end_epoch:
            model_state = {'model_dm_state': self.model_dm.module.state_dict(), 'args': args}
            torch.save(model_state, os.path.join(args.dir_path, 'final_dm_{}.pth'.format(args.model_name)))

    @torch.no_grad()
    def val_save_image(self, dir_path, dataset, val_num=3):
        """
        Placeholder method for saving validation images. 
        Currently only performs inference padding and forward pass but does not save disk outputs.
        """
        os.makedirs(dir_path, exist_ok=True)
        self.model_dm.eval()
        for idx in random.sample(range(0, len(dataset)), val_num):
            sample = dataset[idx]
            blur, sharp = sample['blur'].unsqueeze(0).to(device), sample['sharp'].unsqueeze(0).to(device)
            b, c, h, w = blur.shape
            
            # Pad images to be divisible by 8 (model requirements)
            factor = 8
            h_n = (factor - h % factor) % factor
            w_n = (factor - w % factor) % factor
            blur = torch.nn.functional.pad(blur, (0, w_n, 0, h_n), mode='reflect')
            
            # Inference pass to ensure no crashes during image generation padding logic
            z_pred = self.model_dm(blur)
            # Image saving logic (cv2.imwrite) is omitted here, likely because latent vectors can't be easily visualized

if __name__ == "__main__":
    # --- Hyperparameters and Command Line Arguments Parsing ---
    parser = argparse.ArgumentParser()
    parser.add_argument("--end_epoch", default=3000, type=int)
    parser.add_argument("--start_epoch", default=1, type=int)
    parser.add_argument("--batch_size", default=20, type=int)
    parser.add_argument("--crop_size", default=256, type=int)
    parser.add_argument("--validation_epoch", default=25, type=int)
    parser.add_argument("--check_point_epoch", default=100, type=int)
    parser.add_argument("--init_lr", default=1e-4, type=float)
    parser.add_argument("--min_lr", default=1e-6, type=float)
    parser.add_argument("--gamma", default=0.5, type=float)
    parser.add_argument("--optimizer", default='adam', type=str)
    parser.add_argument("--criterion", default='l1', type=str)
    parser.add_argument("--data_path", default='./dataset/GOPRO_Large', type= str)
    parser.add_argument("--dir_path", default='./experiments/MIMO_UNet/GoPro/stage2', type=str) # Stage 2 path
    parser.add_argument("--model_name", default='BlurDM', type=str)
    parser.add_argument("--model", default='BlurDM', type=str)
    
    # CRUCIAL ADDITION: Path to load the pre-trained Latent Encoder from Stage 1
    parser.add_argument("--model_le_path", default=None, type=str) 
    
    parser.add_argument("--seed", default=2023, type=int)
    parser.add_argument("--val_save_epochs", default=100, type=int)
    parser.add_argument("--resume", default=None, type=str)
    parser.add_argument("--only_use_generate_data", action='store_true', help="only use generated data to train model.")
    parser.add_argument("--num_workers", default=0 if os.name == "nt" else 8, type=int)
    parser.add_argument("--local_rank", default=os.getenv('LOCAL_RANK', -1), type=int)
    
    args = parser.parse_args()

    # --- Distributed Data Parallel (DDP) Initialization ---
    if args.local_rank != -1: # Multi-GPU setup
        if torch.cuda.is_available():
            torch.cuda.set_device(args.local_rank)
            device = torch.device("cuda", args.local_rank)
        else:
            device = torch.device("cpu")
        backend = "nccl" if (torch.cuda.is_available() and dist.is_nccl_available() and os.name != "nt") else "gloo"
        dist.init_process_group(backend=backend, init_method='env://')
    else: # Fallback single GPU/CPU setup
        if torch.cuda.is_available():
            args.local_rank = 0
            torch.cuda.set_device(args.local_rank)
            device = torch.device("cuda", args.local_rank)
        else:
            args.local_rank = 0
            device = torch.device("cpu")
        if not dist.is_initialized():
            master_port = os.getenv("MASTER_PORT", "29500")
            dist.init_process_group(
                backend="gloo",
                init_method=f"tcp://127.0.0.1:{master_port}",
                rank=0,
                world_size=1,
            )

    # --- Initialize Models ---
    net_le = LE_arch() # Latent Encoder
    net_dm = LatentExposureDiffusion() # Diffusion/Predictor Model

    # --- Load Pre-trained Stage 1 Latent Encoder Weights ---
    # We must load the pre-trained teacher model so it provides accurate ground-truth latents
    load_le_model_state = torch.load(args.model_le_path)
    load_le_model_state["model_le_state"] = judge_and_remove_module_dict(load_le_model_state["model_le_state"])
    net_le.load_state_dict(load_le_model_state["model_le_state"])

    # --- Seed Everything for Reproducibility ---
    seed = args.seed + args.local_rank
    torch.backends.cudnn.enabled = True
    torch.backends.cudnn.benchmark = True
    torch.backends.cudnn.deterministic = True
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.cuda.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

    args.device = device
    print("device:", device)
    num_gpus = torch.cuda.device_count()
    
    # Move models to appropriate device
    net_le.to(device)
    net_dm.to(device)

    print(args.__dict__.items())

    # --- Collect Parameters for the Optimizer ---
    optim_params = []
    # ONLY optimize the diffusion model (net_dm). 
    # net_le is omitted here to remain frozen during Stage 2 training.
    for k, v in net_dm.named_parameters():
        if v.requires_grad:
            optim_params.append(v)

    # --- Initialize Optimizer and Scheduler ---
    if args.optimizer == "adam":
        optimizer = optim.Adam([{'params': optim_params}], lr=args.init_lr)
    elif args.optimizer == "adamw":
        optimizer = optim.AdamW([{'params': optim_params}], lr=args.init_lr, weight_decay=1e-4)
    else:
        raise ValueError(f"optimizer not supported {args.optimizer}")

    scheduler = optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.end_epoch, eta_min=args.min_lr)
        
    # --- Load Checkpoints to Resume Training (if applicable) ---
    map_location = {'cuda:%d' % 0: 'cuda:%d' % args.local_rank}
    
    # Auto-resume from last saved checkpoint in the experiment directory
    if os.path.exists(os.path.join(args.dir_path, 'last_{}.pth'.format(args.model_name))):
        print('load_pretrained')
        training_state = (torch.load(os.path.join(args.dir_path, 'last_{}.pth'.format(args.model_name)), map_location=map_location))
        args.start_epoch = training_state['epoch'] + 1
        if 'best_psnr' in training_state['args']:
            args.best_psnr = training_state['args'].best_psnr

        # Load Diffusion Model state
        new_weight = net_dm.state_dict()
        training_state["model_dm_state"] = judge_and_remove_module_dict(training_state["model_dm_state"])
        new_weight.update(training_state['model_dm_state'])
        net_dm.load_state_dict(new_weight)

        # Load Optimizer & Scheduler state
        new_optimizer = optimizer.state_dict()
        new_optimizer.update(training_state['optimizer_state'])
        optimizer.load_state_dict(new_optimizer)
        
        new_scheduler = scheduler.state_dict()
        new_scheduler.update(training_state['scheduler_state'])
        scheduler.load_state_dict(new_scheduler)
        
    # Explicitly resuming from a specific path via argument
    elif args.resume:
        print('load_resume_pretrained')
        model_load = torch.load(args.resume, map_location=map_location)
        model_load["model_dm_state"] = judge_and_remove_module_dict(model_load["model_dm_state"])
        net_dm.load_state_dict(model_load['model_dm_state'])
        os.makedirs(args.dir_path, exist_ok=True)
    else:
        os.makedirs(args.dir_path, exist_ok=True)
    
    # --- Wrap Models in Distributed Data Parallel ---
    net_le = nn.parallel.DistributedDataParallel(net_le, device_ids=[args.local_rank],
                                          output_device=args.local_rank)

    net_dm = nn.parallel.DistributedDataParallel(net_dm, device_ids=[args.local_rank],
                                          output_device=args.local_rank)
                                          
    # --- Datasets and DataLoaders Setup ---
    dataset_name = args.data_path.split('/')[-1]
    train_data_path = args.data_path

    if dataset_name == "GOPRO_Large":
        Train_set = Multi_GoPro_Loader(data_path=train_data_path, mode="train", crop_size=args.crop_size)
    elif (dataset_name == "Realblur_J") or (dataset_name == "Realblur_R"):
        Train_set = RealBlur_Loader(data_path=train_data_path, mode="train", crop_size=args.crop_size, ZeroToOne=False)
    
    train_sampler = DistributedSampler(Train_set)
    dataloader_train = DataLoader(
        Train_set,
        sampler=train_sampler,
        batch_size=args.batch_size // num_gpus,
        num_workers=args.num_workers,
        pin_memory=torch.cuda.is_available(),
    )

    # Validation Set Loader Setup
    if dataset_name == "GOPRO_Large":
        Val_set = Multi_GoPro_Loader(data_path=args.data_path, mode="test", crop_size=args.crop_size)
    elif (dataset_name == "Realblur_J") or (dataset_name == "Realblur_R"):
        Val_set = RealBlur_Loader(data_path=train_data_path, mode="test", crop_size=args.crop_size, ZeroToOne=False)

    dataloader_val = DataLoader(
        Val_set,
        batch_size=args.batch_size // num_gpus,
        shuffle=True,
        num_workers=args.num_workers,
        drop_last=False,
        pin_memory=torch.cuda.is_available(),
    )
    
    writer = None
    # --- Logging Setup (Only on Master Node/Rank 0) ---
    if dist.get_rank() == 0:
        logging.basicConfig(
            filename=os.path.join(args.dir_path, 'train.log') , format='%(levelname)s:%(message)s', encoding='utf-8', level=logging.INFO)
        
        logging.info(f'args: {args}')
        logging.info(f'latent encoder: {net_le}')
        logging.info(f'latent dm encoder: {net_dm}')
        logging.info(f'latent encoder parameters: {count_parameters(net_le)}')
        logging.info(f'latent dm encoder parameters: {count_parameters(net_dm)}')
        logging.info(f"Optimizer:{optimizer.__class__.__name__}")
        logging.info(f"Train Data length:{len(dataloader_train.dataset)}")

        writer = SummaryWriter(os.path.join("MIMO_log", args.model_name))
        writer.add_text("args", str(args))

    # --- Start Training ---
    trainer = Trainer(dataloader_train, dataloader_val, net_le, net_dm,optimizer, scheduler, args, writer)
    trainer.train()
